import { ChevronRightIcon } from '@heroicons/react/solid'
import Head from 'next/head'
import Image from "next/image"

import Footer from '../components/Footer'
import { Header } from '../components/Header'
import { Icon, Icon1, Iconblue, IconNoColor } from '../components/Icon'
import { TabsLanding } from '../components/Tabs'

export default function Home() {

  return (
    <>
      <Head>
        <title>Elementor Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="w-screen h-screen bg-pink">
        <Header />
        <div className="md:w-3/4 mx-auto">
          <div className="pt-32 lg:pt-48 text-center text-black">
            <h1 className="font-boldd text-4xl md:text-7xl font-extrabold">Create Websites,<br />Design Your Future</h1>
            <p className="w-8/12 text-xl md:text-2xl mx-auto my-10">Join our community of 8M+ professionals who build websites, collaborate, and grow together with the #1 web creation platform for WordPress.</p>
            <a className="w-3/6 bg-pinkstronge text-white text-xl py-3 px-5 hover:bg-pinkhover cursor-pointer">Get Started</a>
          </div>
        </div>
      </main>

      <section className="flex flex-col mt-20 relative w-screen">

        <div className="w-10/12 lg:w-8/12 mx-auto ">
          <div className="flex justify-center">
            <video tabIndex="0" preload="true" loop autoPlay className="hidden xl:flex justify-center absolute " style={{ bottom: "96%" }} >
              <source src="https://elementor.com/wp-content/uploads/2021/06/02_MainVideo_1066_600_HR201.mp4" type="video/mp4"></source>
            </video>
            <video tabIndex="0" preload="true" loop autoPlay className="hidden lg:flex xl:hidden justify-center absolute " style={{ bottom: "95%" }} >
              <source src="https://elementor.com/wp-content/uploads/2021/06/02_MainVideo_1066_600_HR201.mp4" type="video/mp4"></source>
            </video>
            <video tabIndex="0" preload="true" loop autoPlay className="hidden md:flex lg:hidden justify-center absolute " style={{ bottom: "97%" }} >
              <source src="https://elementor.com/wp-content/uploads/2021/06/02_MainVideo_1066_600_HR201.mp4" type="video/mp4"></source>
            </video>
            <video tabIndex="0" preload="true" loop autoPlay className="hidden sm:flex md:hidden justify-center absolute " style={{ bottom: "100.5%" }} >
              <source src="https://elementor.com/wp-content/uploads/2021/06/02_MainVideo_1066_600_HR201.mp4" type="video/mp4"></source>
            </video>
            <video tabIndex="0" preload="true" loop autoPlay className="flex sm:hidden justify-center absolute " style={{ bottom: "99.5%" }} >
              <source src="https://elementor.com/wp-content/uploads/2021/06/02_MainVideo_1066_600_HR201.mp4" type="video/mp4"></source>
            </video>
          </div>

          <div className="flex md:hidden lg:flex flex-col md:flex-row justify-between mx-auto mt-20 md:mt-80 lg:mt-96">
            <div className="w-full md:w-3/12 mb-5 ">
              <h1 className="mb-5 font-bold text-xl">Live Drag & Drop Editor</h1>
              <p>Build and customize every part of your website intuitively with Elementor’s visual builder. Zero coding required.</p>
            </div>
            <div className="w-full md:w-3/12 mb-5 ">
              <h1 className="mb-5 font-bold text-xl">90+ Widgets</h1>
              <p>Achieve your design goals with a widget for every need along with full customization freedom.</p>
            </div>
            <div className="w-full md:w-3/12 mb-5 ">
              <h1 className="mb-5 font-bold text-xl">Pixel-Perfect Design</h1>
              <p>Create flawless websites with custom positions, padding, margins, and global settings for colors & typographies.</p>
            </div>
          </div>
          <div>
            <div className="hidden md:flex lg:hidden flex-col md:flex-row justify-between mx-auto mt-20 md:mt-80 lg:mt-96">
              <div className="flex flex-col w-full">
                <div className="w-4/6 mb-5 ">
                  <h1 className="mb-5 font-bold text-xl">Live Drag & Drop Editor</h1>
                  <p>Build and customize every part of your website intuitively with Elementor’s visual builder. Zero coding required.</p>
                </div>
                <div className="w-4/6 mb-5 ">
                  <h1 className="mb-5 font-bold text-xl">90+ Widgets</h1>
                  <p>Achieve your design goals with a widget for every need along with full customization freedom.</p>
                </div>
              </div>
              <div className="w-4/6 mb-5">
                <h1 className="mb-5 font-bold text-xl">Pixel-Perfect Design</h1>
                <p>Create flawless websites with custom positions, padding, margins, and global settings for colors & typographies.</p>
              </div>
            </div>
            <div className="text-center mt-10 md:mb-20 md:mt-32 w-full">
              <h1 className="font-boldd text-6xl md:text-7xl font-extrabold">One Platform, Unlimited Web Creations</h1>
              <p className="text-2xl mx-auto my-10">From landing pages, and eCommerce stores, to full-blown websites – build it all with Elementor.</p>
            </div>
          </div>
          <TabsLanding />
        </div>
        <Icon1 />

        <div className="bg-pinkstronge w-screen mt-10 md:mt-40">
          <div className="flex flex-col md:flex-row justify-between w-10/12 mx-auto py-5">
            <div className="flex flex-col w-full md:w-4/6 mt-20 text-white ">
              <h1 className="text-4xl">“Elementor was the first time I felt a good balance between the freedom to design what you want and a tool flexible enough to make the process easy and even enjoyable.”</h1>
              <p className="text-2xl mt-6 mb-3">Mordi Levi</p>
              <p className="text-1xl">Designer, Illustrator, and Owner of Mindcube</p>
            </div>
            <Image src="/image1.png" width={500} height={500} className="" />
          </div>
        </div>

        <div className="flex flex-col md:flex-row justify-between w-10/12 md:space-x-6 mx-auto my-10 md:mt-20">
          <div className="w-10/12 md:w-2/4">
            <h1 className="text-1xl font-boldd">RESOURCES & SKILLS</h1>
            <h1 className="font-boldd text-5xl font-extrabold my-5">Elevate Your Skills<br />& Grow Professionally</h1>
            <p className="w-full md:w-4/6 font-mediumm text-xl">Our resources and tools are designed to help you learn, grow, and develop your skills at every level.</p>
          </div>

          <div className="w-full md:w-2/4 mt-10">
            <div className="flex flex-row space-x-5 md:space-x-10 mb-10">
              <div className="w-2/4">
                <div>
                  <img src="https://elementor.com/cdn-cgi/image/f=auto,w=305,h=191/wp-content/uploads/2021/05/Frame-1086716.png" />
                </div>
                <div>
                  <h1 className="mt-2 text-2xl font-extrabold">Blog </h1>
                  <p className="mt-3 mb-5 font-mediumm text-xl">Get expert tips on everything web creation & all the latest Elementor news.</p>
                  <a className="font-mediumm tracking-wide text-lg text-pinkstronge border-b border-pinkstronge border-opacity-0 hover:border-opacity-100 cursor-pointer duration-500 inline-flex">Explore More
                    <Icon Icon={ChevronRightIcon} />
                  </a>
                </div>
              </div>
              <div className="w-2/4">
                <div>
                  <img src="https://elementor.com/cdn-cgi/image/f=auto,w=305,h=191/wp-content/uploads/2021/05/Developer-Hub.png" />
                </div>
                <div>
                  <h1 className="mt-2 text-2xl font-extrabold">Developer Hub</h1>
                  <p className="mt-3 mb-5 font-mediumm text-xl">Browse Elementor's extensive library of resources for developers.</p>
                  <a className="font-mediumm tracking-wide text-lg text-pinkstronge border-b border-pinkstronge border-opacity-0 hover:border-opacity-100 cursor-pointer duration-500 inline-flex">Browse Resources
                    <Icon Icon={ChevronRightIcon} />
                  </a>
                </div>
              </div>
            </div>

            <div className="flex flex-row space-x-5 md:space-x-10">
              <div className="w-2/4">
                <div>
                  <img src="https://elementor.com/cdn-cgi/image/f=auto,w=305,h=191/wp-content/uploads/2021/05/academy-2.png" />
                </div>
                <div>
                  <h1 className="mt-2 text-2xl font-extrabold">Tutorials & Courses</h1>
                  <p className="mt-3 mb-5 font-mediumm text-xl">Access hundreds of video tutorials and courses on all things web creation.</p>
                  <a className="font-mediumm tracking-wide text-lg text-pinkstronge border-b border-pinkstronge border-opacity-0 hover:border-opacity-100 cursor-pointer duration-500 inline-flex">Watch Now
                    <Icon Icon={ChevronRightIcon} />
                  </a>
                </div>
              </div>
              <div className="w-2/4">
                <div>
                  <img src="https://elementor.com/cdn-cgi/image/f=auto,w=305,h=191/wp-content/uploads/2021/05/Help.png" />
                </div>
                <div>
                  <h1 className="mt-2 text-2xl font-extrabold">Help Center</h1>
                  <p className="mt-3 mb-5 font-mediumm text-xl">Your go-to place for step-by-step guides on how to use Elementor.</p>
                  <a className="font-mediumm tracking-wide text-lg text-pinkstronge border-b border-pinkstronge border-opacity-0 hover:border-opacity-100 cursor-pointer duration-500 inline-flex">Get Answers
                    <Icon Icon={ChevronRightIcon} />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-graypage w-screen mt-10 md:mt-20">
          <div className="flex flex-col md:flex-row justify-between w-10/12 mx-auto py-5">
            <div className="flex flex-col w-full md:w-4/6 mt-20 ">
              <h1 className="text-4xl text-pinkmedium">“The best thing about Elementor is the community and the great developers behind this ingenious software. It gives me great confidence in the quality of the product & the assurance that Elementor will be around for years to come.”</h1>
              <p className="text-2xl mt-6 mb-3 text-black">Brandon Duncan</p>
              <p className="text-1xl text-gray-600">Owner & Creative Director of Regent Web Design</p>
            </div>
            <Image src="/image3.png" width={500} height={500} className="" />
          </div>
        </div>

        <div className="w-10/12 mx-auto whitespace-none break-all">
          <div className="flex flex-col md:flex-row justify-between my-20">
            <div className="md:w-4/6 mb-10">
              <h1 className="text-1xl font-boldd">COMMUNITY</h1>
              <h1 className="font-boldd text-5xl font-extrabold my-5">Join Our Community of Web Creators</h1>
              <p className="mt-3 mb-5 font-mediumm text-xl">Head over to the Community Hub, meet and engage with other web creators and be the first to learn about new product updates.</p>
              <a className="font-mediumm tracking-wide justify-center text-lg py-3 px-3 text-bluedark border border-bluedark cursor-pointer group duration-500 inline-flex hover:text-white hover:bg-bluedark">Go to the Hub
                <IconNoColor Icon={ChevronRightIcon} className="group-hover:text-white text-bluedark " />
              </a>
            </div>
            <div>
              <img src="https://elementor.com/cdn-cgi/image/f=auto,w=394,h=444/wp-content/uploads/2021/05/Group-1086831-1.png" className="mx-auto object-cover" />
            </div>
          </div>
          <div className="flex sm:hidden lg:flex flex-col lg:flex-row justify-between space-x-6 w-full">
            <div className="flex flex-col p-5 text-center">
              <h1 className="text-5xl sm:text-7xl font-extrabold font-boldd">8M+</h1>
              <p className="font-mediumm text-xl">Websites Built<br />With Elementor</p>
            </div>
            <div className="flex flex-col p-5 text-center">
              <h1 className="text-5xl sm:text-7xl font-extrabold font-boldd">140K+</h1>
              <p className="font-mediumm text-xl">Global Community <br />Members</p>
            </div>
            <div className="flex flex-col p-5 text-center">
              <h1 className="text-5xl sm:text-7xl font-extrabold font-boldd">400+</h1>
              <p className="font-mediumm text-xl">Meetup Events <br />in 2020</p>
            </div>
            <div className="flex flex-col p-5 text-center">
              <h1 className="text-5xl sm:text-7xl font-extrabold font-boldd">330+</h1>
              <p className="font-mediumm text-xl">Tutorials, Webinars, <br />Courses, and More</p>
            </div>
          </div>

          <div className="hidden sm:flex lg:hidden flex-col w-full">
            <div className="flex flex-row justify-between w-11/12 mx-auto">
              <div className="flex flex-col p-5 text-center">
                <h1 className="text-7xl font-extrabold font-boldd">8M+</h1>
                <p className="font-mediumm text-xl">Websites Built<br />With Elementor</p>
              </div>
              <div className="flex flex-col p-5 text-center">
                <h1 className="text-7xl font-extrabold font-boldd">140K+</h1>
                <p className="font-mediumm text-xl">Global Community <br />Members</p>
              </div>
            </div>
            <div className="flex flex-row justify-between w-11/12 mx-auto">
              <div className="flex flex-col p-5 text-center">
                <h1 className="text-7xl font-extrabold font-boldd">400+</h1>
                <p className="font-mediumm text-xl">Meetup Events <br />in 2020</p>
              </div>
              <div className="flex flex-col p-5 text-center">
                <h1 className="text-7xl font-extrabold font-boldd">330+</h1>
                <p className="font-mediumm text-xl">Tutorials, Webinars, <br />Courses, and More</p>
              </div>
            </div>
          </div>
        </div>

        <div className="flex w-full relative">
          <div className="flex flex-col md:flex-row justify-between mt-20">
            <div className="w-full md:w-3/6 text-left">
              <h1 className="text-5xl font-extrabold mb-5 px-5">User Built, User Driven</h1>

              <div className="flex flex-col md:flex-row md:space-x-12 z-30 md:absolute">
                <div className="w-full md:w-5/12 lg:w-3/12 px-10 py-7 bg-bluelight md:mt-20">
                  <h1 className="text-2xl font-mediumm ">Add-Ons by Our Users</h1>
                  <p className="mt-3 mb-5 text-gray-500">Professionals from our community have built custom add-ons for Elementor, extending our vast selection of website templates and widgets.</p>
                  <a className="font-mediumm tracking-wide text-lg text-bluedark border-b border-bluedark border-opacity-0 hover:border-opacity-100 cursor-pointer duration-500 inline-flex">Browse Add-Ons
                    <IconNoColor Icon={ChevronRightIcon} className="text-bluedark" />
                  </a>
                </div>
                <div className="w-full md:w-5/12 lg:w-3/12 px-10 py-7 bg-bluelight md:mt-20 mx-auto">
                  <h1 className="text-2xl font-mediumm ">Build Your Own</h1>
                  <p className="mt-3 mb-5 text-gray-500">Built as an open-source tool with extensive API, Elementor enables you to extend our product by developing your own templates and widgets.</p>
                  <a className="font-mediumm tracking-wide text-lg text-bluedark border-b border-bluedark border-opacity-0 hover:border-opacity-100  transition ease-in-expo cursor-pointer duration-500 inline-flex">Learn More
                    <IconNoColor Icon={ChevronRightIcon} className="text-bluedark" />
                  </a>
                </div>
              </div>
            </div>
            <div className="w-full md:w-3/6">
              <img src="https://hrs-corporate-prod.s3.eu-west-1.amazonaws.com/wp-content/uploads/sites/2/2021/03/16105521/hrs-enterprise-meetings-as-a-service-1-1024x686.jpg" />
            </div>
          </div>
        </div>

        <div className="w-10/12 mx-auto">
          <div className="flex flex-col lg:flex-row justify-between space-x-20 my-5 md:mt-40">
            <div className="md:w-3/6 mb-10">
              <h1 className="text-1xl font-boldd">ELEMENTOR EXPERTS</h1>
              <h1 className="font-boldd text-5xl font-extrabold my-5">Find Your Next Project With Elementor Experts</h1>
              <p className="mt-3 mb-5 font-mediumm text-xl lg:w-5/6">Find a developer, designer, or business professional for your project or get hired as an expert yourself.</p>
              <a className="font-mediumm tracking-wide text-lg py-3 text-orangedark border-b border-orangedark border-opacity-0 cursor-pointer duration-500 inline-flex hover:border-opacity-100">Learn More
                <IconNoColor Icon={ChevronRightIcon} className="text-orangedark" />
              </a>
            </div>
            <div className="hidden lg:flex mb-10 md:mb-52 w-full md:w-3/6">
              <img src="https://elementor.com/cdn-cgi/image/f=auto,w=690/wp-content/uploads/2021/05/Group-1086831-1-1-1.png" className="md:relative w-full object-cover" />
              <div className="hidden xl:flex">
                <img src="https://elementor.com/cdn-cgi/image/f=auto,w=403,h=483/wp-content/uploads/2021/05/Group-1086708.png" className="md:absolute z-10 object-cover" style={{ width: "200px", height: "250px", top: "85%", left: "45%" }} />
                <img src="https://elementor.com/cdn-cgi/image/f=auto,w=403,h=483/wp-content/uploads/2021/05/Group-1086706.png" className="md:absolute z-10 object-cover" style={{ width: "200px", height: "250px", top: "85%", left: "60%" }} />
                <img src="https://elementor.com/cdn-cgi/image/f=auto,w=404,h=484/wp-content/uploads/2021/05/Group-1086707-1.png" className="md:absolute z-10 object-cover" style={{ width: "200px", height: "250px", top: "85%", left: "75%" }} />
              </div>
              <div className="hidden lg:flex xl:hidden">
                <img src="https://elementor.com/cdn-cgi/image/f=auto,w=403,h=483/wp-content/uploads/2021/05/Group-1086708.png" className="md:absolute z-10 object-cover" style={{ width: "150px", height: "200px", top: "85%", left: "50%" }} />
                <img src="https://elementor.com/cdn-cgi/image/f=auto,w=403,h=483/wp-content/uploads/2021/05/Group-1086706.png" className="md:absolute z-10 object-cover" style={{ width: "150px", height: "200px", top: "85%", left: "65%" }} />
                <img src="https://elementor.com/cdn-cgi/image/f=auto,w=404,h=484/wp-content/uploads/2021/05/Group-1086707-1.png" className="md:absolute z-10 object-cover" style={{ width: "150px", height: "200px", top: "85%", left: "80%" }} />
              </div>
            </div>
          </div>
          <div className="flex flex-col md:flex-row justify-between md:space-x-6">
            <div className="w-full md:w-3/12 mb-5">
              <h1 className="text-2xl font-mediumm mb-5">Grow Your Business</h1>
              <p className="font-mediumm text-lg text-gray-500">Create your expert profile, present your best work, and get hired for design, marketing, and developement projects.</p>
            </div>
            <div className="w-full md:w-3/12 mb-5 ">
              <h1 className="text-2xl font-mediumm mb-5">Hire an Expert</h1>
              <p className="font-mediumm text-lg text-gray-500">Browse our Elementor experts and find a designer, marketer, or developer to help with your next project.</p>
            </div>
            <div className="w-full md:w-3/12 mb-5 ">
              <h1 className="text-2xl font-mediumm mb-5">Collaborate With Others</h1>
              <p className="font-mediumm text-lg text-gray-500">Join our platform of professionals to exchange knowledge, share hacks, and join forces.</p>
            </div>
          </div>
        </div>

        <div className="bg-orangelight py-10 mt-20">
          <div className="flex flex-col md:flex-row justify-between md:space-x-5 w-10/12 mx-auto">
            <div className="w-10/12 md:w-3/6 mb-10">
              <h1 className="font-boldd text-5xl font-extrabold my-5">Meet Elementor's Live Editor</h1>
              <p className="mt-3 mb-5 font-mediumm text-xl">Visualize & build your website from top to bottom.<br />Drag & drop any widget or section onto your canvas – zero coding required.</p>
              <a className="font-mediumm tracking-wide justify-center text-lg py-3 px-3 text-orangedark border border-orangedark cursor-pointer group duration-500 inline-flex hover:text-white hover:bg-orangedark">Explore the Editor
                <IconNoColor Icon={ChevronRightIcon} className="group-hover:text-white text-orangedark" />
              </a>
            </div>
            <div className="w-full md:w-3/6 my-auto">
              <img src="https://elementor.com/cdn-cgi/image/f=auto,w=739/wp-content/uploads/2021/05/Group-1086839-1.png" className="object-cover mx-auto" />
            </div>
          </div>
        </div>

      </section>


      <Footer />
    </>
  )
}





